spring:
  application:
    name: workflow-orchestrator
#  datasource:
#    url: jdbc:sqlserver://localhost:1434;databaseName=workflow_db;encrypt=false
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    username: workflow_db
#    password: test123
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
    out-of-order: false  # Prevent out-of-order migrations

    # Development settings
    clean-on-validation-error: false  # Never auto-clean

    # Production safety
    clean-disabled: true  # Prevent accidental clean in prod
  datasource:
    url: jdbc:h2:mem:workflow_db
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  h2:
    console:
      enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

workflow:
  task:
    execution:
      thread-pool-size: 10
    retry:
      max-attempts: 3
      initial-interval: 1000
      multiplier: 2.0
  events:
    enabled: true
